-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "submittedById" SET DATA TYPE BIGINT,
ALTER COLUMN "messageId" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "EventArchive" ALTER COLUMN "submittedById" SET DATA TYPE BIGINT,
ALTER COLUMN "messageId" SET DATA TYPE BIGINT;
