export const ICONS = {
  pensil: '✏️',
  announcement: '📢',
  location: '📍',
  date: '📅',
  category: '🏷',
  description: '📝',
  links: '🔗',
  approve: '✅',
  reject: '❌',
  search: '🔍',
  reset: '🔄',
  edit: '✏️',
  by: '👤',
  update: '🔄',
  save: '💾',
  image: '🖼',
  happy: '😊',
  sad: '😞',
  warning: '⚠️',
  error: '❌',
  success: '✅',
  info: 'ℹ️',
  help: '❓',
  back: '🔙',
  birthday: '🎂',
  event: '🎉',
  reminder: '⏰',
  settings: '⚙️',
  attention: '⚠️',
  tip: '👆',
  next: '➡️',
  group: '👥',
  email: '📧',
  telegram: '➡️',
  rules: '📜',
  template: '📋',
  list: '📋',
  delete: '🗑️',
  calendar: '📅',
  push: '🚀',
};
